# Generated by Django 3.2.18 on 2023-02-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='desription',
            new_name='description',
        ),
    ]
